# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
	# check these on https://fabricmc.net/versions.html
minecraft_version=1.20.1
loader_version=0.19.3
yarn_mappings=1.20.1+build.10
loom_version=1.17-SNAPSHOT

#libGui
libgui_version=8.1.1+1.20.1


# Mod Properties
mod_version = 1.1.0-dev-u1
maven_group = io.gtihub.aftersans53228

# Dependencies
#Fabric api
fabric_api_version=0.92.7+1.20.1

